### ISSUE TITLE
fix: Incorrect @types/validator dependency in latest version (0.13.0)

### ISSUE THREAD

**Issue by kiancross** [typestack/class-validator#869]
### Description

In 749fb26281a73ef43ce7e297f8b92be8a419c8cb, `@types/validator` was moved from `dependencies` to `devDependencies`. 

This causes those without `skipLibCheck` set to `true` to get build errors, as `validator` is used in many of the generated type definitions.

**Comment by bennycode** [comment]
When bumping "class-validator" from 0.12.2 to 0.13.0, I was also getting this error:

> import ValidatorJS from 'validator';
>                          ~~~~~~~~~~~
>
> node_modules/class-validator/types/decorator/string/IsNumberString.d.ts:2:25 - error TS7016: Could not find a declaration file > for module 'validator'. 'C:/dev/projects/bennycode/lambot-1/node_modules/validator/index.
> js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/validator` if it exists or add a new declaration (.d.ts) file containing `declare module 'validator';`

@NoNameProvided, can you release a hotfix (v0.13.1)?

**Comment by tet-lenovo** [comment]
Any idea when this patch will be released?

**Comment by kiancross** [comment]
If you are using Yarn 2, you can add the following to your `.yarnrc.yml` file as a temporary fix:

```yaml
packageExtensions:    
  class-validator@*:    
    dependencies:    
      "@types/validator": ^13.1.3 
```

**Comment by tet-lenovo** [comment]
Adding it to my package dependencies does fix it but, not ideal so backed out the update for now.
