### ISSUE TITLE
fix: 0.13.2 to 0.14.0 breaks IsCurrencyOptions

### ISSUE THREAD

**Issue by ifm-studio** [typestack/class-validator#1923]
### Description

When upgrading from 0.13.2 to 0.14.0 (package,json) my packages receive the following error, which is not implicitly outlined in the breaking changes.

```
Error: src/cat-rock.ts(39,9): error TS2345: Argument of type '{ symbol: string; allow_negatives: false; require_symbol: false; require_decimal: true; message: string; }' is not assignable to parameter of type 'IsCurrencyOptions'.
Object literal may only specify known properties, and 'message' does not exist in type 'IsCurrencyOptions'.
```

The change log mentions this was removed in 0.10.0 and replaced with interfaces from:

>    remove IsCurrencyOptions, IsURLOptions, IsEmailOptions, IsFQDNOptions interfaces and replace with interfaces from @types/validator

https://github.com/typestack/class-validator/blob/0c30684ffce9ce4f4cf91182e0be406e8a4cae6a/CHANGELOG.md#breaking-changes-3

### Expected behavior

~~General comment, semver minor upgrades should not break code.~~
~~https://semver.org/~~

Wondering migration path -- would be helpful to have in docs?

Can these options still be supported?
{ symbol: string; allow_negatives: false; require_symbol: false; require_decimal: true; message: string; }' is not assignable to parameter of type 'IsCurrencyOptions'.

### Actual behavior

Code fails.
No migration path mention in docs.

Thank you.

**Comment by braaar** [comment]
As you can see on semver.org:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

In `class-validator` and other projects on version 0, minor version upgrades (`0.13.2 -> 0.14.0`) are typically understood to come with breaking changes, and patch versions /`0.13.0 -> 0.13.1`) are not breaking.

You are right that this project can feel somewhat lacking in the documentation department, and patch notes and migration guides are not as thorough as they could be. I haven't been involved with the project for very long, but I believe there is an intention to focus more efforts in that direction (such as making a docs website) once the API is more stable and established. 

However, all contributions to the readme-based documentation are greatly appreciated. If you would like to amend the changelog with this breaking change, feel free to open a PR :)

**Comment by ifm-studio** [comment]
Thanks semver for the clarification :cat: .

Question, is the correct course of action to:
* Update the changelog to say it was removed?
* Should it be looked into why 'message' is no longer 'IsCurrencyOptions' interface?
* or something else?

Quickly, looks like @types/validator doesn't feature a message field:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/06a22dd74f1011c327337ce7bb80e56cd483cdbf/types/validator/index.d.ts#L279

**Comment by braaar** [comment]
If the fault lies in `@types/validator` I think it should be addressed there. If you could look into the history of the code in validatorjs and @types/validator you might be able to figure out if the validator code itself was changed or this is just a mistake in the type declarations.

It seems like it would be correct to list this in the changelog as a breaking change.

This is not the first issue with types I've come across recently (see #1866), so I think there is reason to go through the types we are getting from @types/validator to make sure they are correct and are all resolving properly.
