### ISSUE TITLE
question: Validating objects of generic classes

### ISSUE THREAD

**Issue by Sauermann** [typestack/class-validator#888]
**I was trying to...**
 
 
In a client-server application I have on the clientside a single function handling API-access and class validation that looks like this and works correctly up until version 0.12.2:

```typescript
  async fetch_api_data<T>(responseClass: Type<T>): Promise<T> {
    const response: Response = await fetch('url', {method: ..., headers: ..., ...});
    const json = await response.json();
    const json_object:T = plainToClass<T, unknown>(responseClass, json);
    const err = await validate(json_object, { whitelist: true, forbidNonWhitelisted: true });
    if (err...) {...}
    return json_object;
  }
```

**The problem:**
 

After the update to V0.13.1, I am getting the following error during compilation:

```
Error: api.ts:119:32 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(object: object, validatorOptions?: ValidatorOptions): Promise<ValidationError[]>', gave the following error.
    Argument of type 'T' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(schemaName: string, object: object, validatorOptions?: ValidatorOptions): Promise<ValidationError[]>', gave the following error.
    Argument of type 'T' is not assignable to parameter of type 'string'.

119     const err = await validate(json_object, { whitelist: true, forbidNonWhitelisted: true });
```

**The questions:**
I understand that the signature of the validate function changed from 
`export function validate(object: Object, validatorOptions?: ValidatorOptions): Promise<ValidationError[]>;` to
`export function validate(object: object, validatorOptions?: ValidatorOptions): Promise<ValidationError[]>;` in PR #591 "build: replace tslint with eslint" during the transition from tslint to eslint.

1. Was it intentional to change the functionality of this library during the transition from tslint to eslint?
2. What is the best practice since v0.13.0 to validate objects of generic classes?

**Comment by Sauermann** [comment]
I found a solution for my question 2.

Replacing
```typescript
const err = await validate(json_object, { whitelist: true, forbidNonWhitelisted: true });
```
with
```typescript
const err = await validate(json_object as unknown as Record<string, unknown>, { whitelist: true, forbidNonWhitelisted: true });
```
removes the compilation error but keeps the ability to validate json_object.
